services:
  mysql:
    image: mysql:8.0
    container_name: mysql_kimp
    ports:
      - "3306:3306"
    env_file:
      - .env
    volumes:
      - ./mysql/data:/var/lib/mysql
    restart: always

  influxdb:
    image: influxdb:2.7
    container_name: influxdb_kimp
    ports:
      - "8086:8086"
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME: admin
      DOCKER_INFLUXDB_INIT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      DOCKER_INFLUXDB_INIT_ORG: kimp-org
      DOCKER_INFLUXDB_INIT_BUCKET: kimp-bucket
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: ${INFLUXDB_TOKEN}
    volumes:
      - ./influxdb/data:/var/lib/influxdb2
    restart: always

  backend:
    image: corqu/kimp-be:0.0.8
    container_name: backend_kimp
    env_file:
      - .env
    environment:
      APP_SECURITY_REQUIRE_SSL: "false"
      APP_SECURITY_SECURE_COOKIES: "true"
    depends_on:
      - mysql
      - influxdb
    expose:
      - "8080"
    restart: always

  frontend:
    image: corqu/kimp-fe:0.0.4
    container_name: frontend_kimp
    depends_on:
      - backend
    expose:
      - "80"
    restart: always

  nginx:
    image: nginx:1.27-alpine
    container_name: nginx_kimp
    depends_on:
      - backend
      - frontend
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Backend/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./Backend/certs:/etc/nginx/certs:ro
    restart: always
